version: "3.8"
services:
    mongo-service:
        restart: always
        image: mongo:latest
        container_name: mongo-container
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
    mongo-express-service:
        restart: always
        image: mongo-express:latest
        container_name: mongo-express-container
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        depends_on:
            - mongo-service
